### ISSUE TITLE
Error in GCP Composer

### ISSUE THREAD

**Issue by pedrofelipest** [gocardless/airflow-dbt#8]
When I run in the composer it returns that.

```
[2020-04-16 21:27:07,642] {taskinstance.py:862} INFO - Executing <Task(DbtRunOperator): dbt_run> on 2020-04-16T21:26:19.688956+00:00
[2020-04-16 21:27:07,643] {base_task_runner.py:133} INFO - Running: ['airflow', 'run', 'dw_dbt', 'dbt_run', '2020-04-16T21:26:19.688956+00:00', '--job_id', '1004', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/dw_dbt/dw_dbt_airflow.py', '--cfg_path', '/tmp/tmph61y8y0e']
[2020-04-16 21:27:09,486] {base_task_runner.py:115} INFO - Job 1004: Subtask dbt_run [2020-04-16 21:27:09,486] {settings.py:254} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=1044
[2020-04-16 21:27:09,800] {base_task_runner.py:115} INFO - Job 1004: Subtask dbt_run [2020-04-16 21:27:09,800] {app.py:53} WARNING - Using default Composer Environment Variables. Overrides have not been applied.
[2020-04-16 21:27:09,803] {base_task_runner.py:115} INFO - Job 1004: Subtask dbt_run [2020-04-16 21:27:09,802] {configuration.py:593} INFO - Reading the config from /etc/airflow/airflow.cfg
[2020-04-16 21:27:09,818] {base_task_runner.py:115} INFO - Job 1004: Subtask dbt_run [2020-04-16 21:27:09,818] {settings.py:254} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=1044
[2020-04-16 21:27:10,185] {base_task_runner.py:115} INFO - Job 1004: Subtask dbt_run [2020-04-16 21:27:10,184] {default_celery.py:90} WARNING - You have configured a result_backend of redis://airflow-redis-service.default.svc.cluster.local:6379/0, it is highly recommended to use an alternative result_backend (i.e. a database).
[2020-04-16 21:27:10,187] {base_task_runner.py:115} INFO - Job 1004: Subtask dbt_run [2020-04-16 21:27:10,187] {__init__.py:51} INFO - Using executor CeleryExecutor
[2020-04-16 21:27:10,188] {base_task_runner.py:115} INFO - Job 1004: Subtask dbt_run [2020-04-16 21:27:10,188] {dagbag.py:407} INFO - Filling up the DagBag from /home/airflow/gcs/dags/dw_dbt/dw_dbt_airflow.py
[2020-04-16 21:27:10,194] {base_task_runner.py:115} INFO - Job 1004: Subtask dbt_run /opt/python3.6/lib/python3.6/site-packages/airflow_dbt/operators/dbt_operator.py:43: PendingDeprecationWarning: Invalid arguments were passed to DbtRunOperator (task_id: dbt_run). Support for passing such arguments will be dropped in Airflow 2.0. Invalid arguments were:
[2020-04-16 21:27:10,194] {base_task_runner.py:115} INFO - Job 1004: Subtask dbt_run *args: ()
[2020-04-16 21:27:10,194] {base_task_runner.py:115} INFO - Job 1004: Subtask dbt_run **kwargs: {'profile_dir': './dw-dbt/profiles'}
[2020-04-16 21:27:10,195] {base_task_runner.py:115} INFO - Job 1004: Subtask dbt_run   super(DbtBaseOperator, self).__init__(*args, **kwargs)
[2020-04-16 21:27:10,619] {base_task_runner.py:115} INFO - Job 1004: Subtask dbt_run [2020-04-16 21:27:10,619] {cli.py:545} INFO - Running <TaskInstance: dw_dbt.dbt_run 2020-04-16T21:26:19.688956+00:00 [running]> on host airflow-worker-67465d97c9-v7q2l
[2020-04-16 21:27:10,685] {base_task_runner.py:115} INFO - Job 1004: Subtask dbt_run [2020-04-16 21:27:10,684] {dbt_hook.py:86} INFO - dbt run --models l1_autorizacoes
[2020-04-16 21:27:10,835] {taskinstance.py:1059} ERROR - [Errno 2] No such file or directory: 'dbt': 'dbt'
Traceback (most recent call last)
  File "/usr/local/lib/airflow/airflow/models/taskinstance.py", line 930, in _run_raw_tas
    result = task_copy.execute(context=context
  File "/opt/python3.6/lib/python3.6/site-packages/airflow_dbt/operators/dbt_operator.py", line 61, in execut
    self.hook.run_cli('run'
  File "/opt/python3.6/lib/python3.6/site-packages/airflow_dbt/hooks/dbt_hook.py", line 93, in run_cl
    close_fds=True
  File "/opt/python3.6/lib/python3.6/subprocess.py", line 729, in __init_
    restore_signals, start_new_session
  File "/opt/python3.6/lib/python3.6/subprocess.py", line 1364, in _execute_chil
    raise child_exception_type(errno_num, err_msg, err_filename
FileNotFoundError: [Errno 2] No such file or directory: 'dbt': 'dbt
```

**Comment by andrewrjones** [comment]
Hey @pedrofelipest,

Noticed you've closed this so you've probably already worked it out, but just for prosperity, this is the error you get when `dbt` isn't on your `PATH`. The operator just calls the `dbt` CLI (there's no other way to invoke it).

If it's not on your `PATH` you can set `dbt_bin` to the absolute path of the `dbt` CLI.

Hope you find this operator useful, and let us know if you have any feedback!

Regards,
Andrew
